### ISSUE TITLE
Play Youtube sound

### ISSUE THREAD

**Issue by jadjay** [azlux/MumbleRadioPlayer#16]
Is there a way to play youtube video sound ?

**Comment by azlux** [comment]
read #11 there are few info here. Ask if you need more !

**Comment by jadjay** [comment]
Hum okay ... It is against youtube terms : https://stackoverflow.com/questions/26548884/is-there-a-youtube-api-that-gives-only-audio

So it won't work out, beside finding an api which offer to play a stream of a youtube url...

Ok thanks,

**Comment by azlux** [comment]
It's not the main problem (we have youtube-dl library for that), but I need to rewrite the all bot for that (I will do it, but I need time and motivation)

**Comment by thejustsoul** [comment]
Some time did not use bots at all, now looking for a suitable option, a few (no order):

- Ability to play audio from a variety of sources without authorization (using ffmpeg, youtube-dl, streamlink, wget, curl, aria2c, etc.).
For example, direct links to audio/video files, links to youtube audio/video/playlists, live broadcasts (both radio streams and live streams youtube, twitch, etc.) without downloading locally (or minimal caching), and the ability to play local files. In general, need a universal player -)
- Support for mumble-certificate (for authorization certificate for mumble-server)
- Support auto-join the channel and reconnection in case of a fall\of disconnection and remembering the last channel before the drop/disconnect
- There is an option to ignore the server certificate (for example, the server and the bot on one machine and the connection is 127.0.0.1)
- Ability to restrict / split user access rights to the bot (type ACL)
- Various bot/playback control options - volume control/stop/start/pause/skip track, clear cache (if available), etc.
- So that the sound does not disappear and is not interrupted / distorted when the stream goes
- To work steadily, was lightweight and minimal consumption of server resources

That's probably a tiny wish list.. maybe he missed something. Maybe something will appear in some kind of bot or all at once, it would be wonderful, yet still are interested in that -)

**Comment by azlux** [comment]
Watch for the project https://github.com/azlux/botamusique that will be my next bot (radio + online music (youtubedl) + local music).
It will not be ready really fast, but I will do it.
