### ISSUE TITLE
Syntax exemple of !playfile ?

### ISSUE THREAD

**Issue by slipenbois** [azlux/MumbleRadioPlayer#4]
Hello,
!list work and find me something.mp3 but when  i try !playfile something.mp3 the bot return bad file asked

Can you give me the exact syntax i'm supposed to send for correctly playing this or i am mistaking and the bot only play specific type of files?

**Comment by azlux** [comment]
Hi,
Into the configuration.ini you need to change the variable `music_folder`. In my case it's `/home/dmichel/pymumble_v3/music/` . Don't forget the last `/` because I just add the folder string with the name you put after the !playfile command `path = self.config.get('bot', 'music_folder') + parameter`.
 So when you want to play a music saved in that folder, write `!playfile music.mp3`.

If you want to check the music path, add `print(path)` after the line 82.
The bot can play all kind of music you know, [ffmpeg is really powerfull](https://ffmpeg.org/general.html#Audio-Codecs).

**Comment by slipenbois** [comment]
Thx  
"/" added  in the end of "music_folder = /home/pi/music"  for "music_folder = /home/pi/music/"
Now it work!
